import type { CatalogModel } from './types'

/**
 * 전체 모델 카탈로그
 *
 * enabled 여부와 무관하게 알려진 모든 모델을 등록한다.
 * 새 모델 추가 시 이 배열에 항목만 추가하면 된다.
 */
export const MODEL_CATALOG: CatalogModel[] = [
  // ─── Video: Image-to-Video ───
  {
    id: 'kling/v2-5-turbo-image-to-video-pro',
    label: 'Kling 2.5 Turbo',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: '최저가 고품질 비디오',
    meta: { quality: 'high', speed: 'fast', cost: 'low', badge: '최저가', priceNote: '$0.21/5s' },
    constraints: { durations: ['5', '10'], aspectRatios: [], supportsEndFrame: true },
  },
  {
    id: 'kling-2.6/image-to-video',
    label: 'Kling 2.6',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: '저렴한 고품질 비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'low', priceNote: '$0.28/5s' },
    constraints: { durations: ['5', '10'], supportsSound: true, supportsEndFrame: true },
  },
  {
    id: 'fal-ai/kling-video/v2.6/pro/image-to-video',
    label: 'Kling 2.6 Pro',
    provider: 'fal',
    capabilities: ['image-to-video'],
    description: '안정적인 프리미엄',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', badge: '안정적', priceNote: '$0.35/5s' },
    constraints: { durations: ['5', '10'], aspectRatios: [], supportsSound: true, supportsEndFrame: true },
  },
  {
    id: 'fal-ai/minimax/hailuo-02/standard/image-to-video',
    label: 'Hailuo 02 Std',
    provider: 'fal',
    capabilities: ['image-to-video'],
    description: '768p 경제적 비디오',
    meta: { quality: 'standard', speed: 'standard', cost: 'low', priceNote: '$0.27/6s' },
    constraints: { durations: ['6', '10'], videoResolutions: ['512p', '768p'], aspectRatios: [], supportsEndFrame: true },
  },
  {
    id: 'fal-ai/minimax/hailuo-02/pro/image-to-video',
    label: 'Hailuo 02 Pro',
    provider: 'fal',
    capabilities: ['image-to-video'],
    description: '1080p 프리미엄 비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.48/6s' },
    constraints: { durations: ['6', '10'], videoResolutions: ['1080p'], aspectRatios: [], supportsEndFrame: true },
  },

  // ─── Video: Kling 2.6 T2V ───
  {
    id: 'kling-2.6/text-to-video',
    label: 'Kling 2.6',
    provider: 'kieai',
    capabilities: ['text-to-video'],
    description: '저렴한 텍스트→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'low', priceNote: '$0.28/5s' },
    constraints: { durations: ['5', '10'], supportsSound: true },
  },
  // ─── Video: Kling 3.0 ───
  {
    id: 'kling-3.0/video',
    label: 'Kling 3.0',
    provider: 'kieai',
    capabilities: ['image-to-video', 'text-to-video'],
    description: '차세대 Kling (I2V+T2V)',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', badge: '최신', priceNote: '$0.56/5s' },
    constraints: { durations: ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'], aspectRatios: ['16:9', '9:16', '1:1'], supportsSound: true },
  },
  {
    id: 'fal-ai/kling-video/v3/standard/image-to-video',
    label: 'Kling 3.0 (fal)',
    provider: 'fal',
    capabilities: ['image-to-video'],
    description: 'Kling 3.0 via fal.ai',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.60/5s' },
    constraints: { durations: ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'], aspectRatios: ['16:9', '9:16', '1:1'], supportsSound: true, supportsEndFrame: true },
  },
  {
    id: 'fal-ai/kling-video/v3/standard/text-to-video',
    label: 'Kling 3.0 (fal)',
    provider: 'fal',
    capabilities: ['text-to-video'],
    description: 'Kling 3.0 T2V via fal.ai',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.60/5s' },
    constraints: { durations: ['3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'], aspectRatios: ['16:9', '9:16', '1:1'], supportsSound: true },
  },
  // ─── Video: Sora 2 ───
  {
    id: 'sora-2-image-to-video',
    label: 'Sora 2',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: 'OpenAI Sora 2 이미지→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$0.80/10s' },
    constraints: { durations: ['10', '15'], aspectRatios: ['16:9', '9:16'] },
  },
  {
    id: 'sora-2-pro-image-to-video',
    label: 'Sora 2 Pro',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: 'OpenAI Sora 2 Pro 이미지→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$1.20/10s' },
    constraints: { durations: ['10', '15'], aspectRatios: ['16:9', '9:16'] },
  },
  {
    id: 'sora-2-text-to-video',
    label: 'Sora 2',
    provider: 'kieai',
    capabilities: ['text-to-video'],
    description: 'OpenAI Sora 2 텍스트→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$0.80/10s' },
    constraints: { durations: ['10', '15'], aspectRatios: ['16:9', '9:16'] },
  },
  {
    id: 'sora-2-pro-text-to-video',
    label: 'Sora 2 Pro',
    provider: 'kieai',
    capabilities: ['text-to-video'],
    description: 'OpenAI Sora 2 Pro 텍스트→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$1.20/10s' },
    constraints: { durations: ['10', '15'], aspectRatios: ['16:9', '9:16'] },
  },
  // ─── Video: Seedance ───
  {
    id: 'bytedance/seedance-1.5-pro',
    label: 'Seedance 1.5 Pro',
    provider: 'kieai',
    capabilities: ['image-to-video', 'text-to-video'],
    description: 'ByteDance 고품질 비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', badge: '추천', priceNote: '$0.44/8s' },
    constraints: { durations: ['4', '8', '12'], videoResolutions: ['720P', '1080P', '480P'], aspectRatios: [] },
  },
  // ─── Video: Hailuo ───
  {
    id: 'hailuo/2-3-image-to-video-pro',
    label: 'Hailuo 2.3 Pro',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: 'Hailuo Pro 이미지→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.48/6s' },
    constraints: { durations: ['6', '10'], videoResolutions: ['768P', '1080P'], aspectRatios: [] },
  },
  {
    id: 'fal-ai/minimax/hailuo-02/pro/text-to-video',
    label: 'Hailuo 02 Pro',
    provider: 'fal',
    capabilities: ['text-to-video'],
    description: 'Hailuo Pro 텍스트→비디오',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.48/6s' },
    constraints: { durations: ['6', '10'], videoResolutions: ['1080p'], aspectRatios: [] },
  },
  // ─── Video: Wan ───
  {
    id: 'wan/2-6-image-to-video',
    label: 'Wan 2.6',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: 'Alibaba Wan 이미지→비디오',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', priceNote: '$0.15/5s' },
    constraints: { durations: ['5', '10', '15'], videoResolutions: ['720p', '1080p'], aspectRatios: [] },
  },
  {
    id: 'wan/2-6-text-to-video',
    label: 'Wan 2.6',
    provider: 'kieai',
    capabilities: ['text-to-video'],
    description: 'Alibaba Wan 텍스트→비디오',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', priceNote: '$0.15/5s' },
    constraints: { durations: ['5', '10', '15'], videoResolutions: ['720p', '1080p'], aspectRatios: [] },
  },
  // ─── Video: Grok ───
  {
    id: 'grok-imagine/image-to-video',
    label: 'Grok',
    provider: 'kieai',
    capabilities: ['image-to-video'],
    description: 'xAI Grok 이미지→비디오',
    meta: { quality: 'standard', speed: 'fast', cost: 'medium', priceNote: '$0.40/6s' },
    constraints: { durations: ['6', '10'], videoResolutions: ['480p', '720p'], aspectRatios: [] },
  },
  // ─── Video: Veo3 ───
  {
    id: 'veo3',
    label: 'Veo 3',
    provider: 'kieai',
    capabilities: ['image-to-video', 'text-to-video'],
    description: 'Google Veo 3 최고 품질',
    meta: { quality: 'high', speed: 'standard', cost: 'high', badge: '최고품질', priceNote: '$1.00/8s' },
    constraints: { durations: ['8'], aspectRatios: [], videoResolutions: ['720p', '1080p'] },
  },
  {
    id: 'veo3_fast',
    label: 'Veo 3 Fast',
    provider: 'kieai',
    capabilities: ['image-to-video', 'text-to-video'],
    description: 'Google Veo 3 빠른 버전',
    meta: { quality: 'high', speed: 'fast', cost: 'high', priceNote: '$0.70/8s' },
    constraints: { durations: ['8'], aspectRatios: [], videoResolutions: ['720p', '1080p'] },
  },
  {
    id: 'fal-ai/veo3',
    label: 'Veo 3 (fal)',
    provider: 'fal',
    capabilities: ['image-to-video', 'text-to-video'],
    description: 'Google Veo 3 via fal.ai',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$1.10/8s' },
    constraints: { durations: ['4', '6', '8'], aspectRatios: ['16:9', '9:16'], videoResolutions: ['720p', '1080p'], supportsSound: true },
  },
  // ─── Video: Runway ───
  {
    id: 'runway/generate',
    label: 'Runway Gen-3',
    provider: 'kieai',
    capabilities: ['image-to-video', 'text-to-video'],
    description: 'Runway Gen-3 Alpha Turbo',
    meta: { quality: 'high', speed: 'fast', cost: 'high', priceNote: '$0.50/10s' },
    constraints: { durations: ['5', '10'], aspectRatios: [] },
  },
  // ─── Video: Luma ───
  {
    id: 'fal-ai/luma-dream-machine/ray-2-flash',
    label: 'Luma Ray 2 Flash',
    provider: 'fal',
    capabilities: ['text-to-video'],
    description: '최저가 텍스트→비디오',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', badge: '최저가', priceNote: '$0.20/5s' },
    constraints: { durations: ['5', '9'], aspectRatios: ['16:9', '9:16', '4:3', '3:4', '21:9'], videoResolutions: ['540p', '720p', '1080p'] },
  },

  // ─── Image: Text-to-Image / Image-to-Image ───

  // Flux 2 Pro (BFL)
  {
    id: 'fal-ai/flux-2-pro',
    label: 'Flux 2 Pro',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: '고품질 프로 이미지 생성',
    meta: { quality: 'high', speed: 'standard', cost: 'low', badge: '추천', priceNote: '$0.03/MP' },
  },
  {
    id: 'fal-ai/flux-2-pro/edit',
    label: 'Flux 2 Pro Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: '고품질 프로 이미지 편집',
    meta: { quality: 'high', speed: 'standard', cost: 'low', badge: '추천', priceNote: '$0.03/MP' },
  },
  // Flux 2 Flex (BFL)
  {
    id: 'fal-ai/flux-2-flex',
    label: 'Flux 2 Flex',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: '조절 가능한 창의성 수준',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.05/MP' },
  },
  {
    id: 'fal-ai/flux-2-flex/edit',
    label: 'Flux 2 Flex Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: '유연한 이미지 편집',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.05/MP' },
  },
  // Flux 2 Max (BFL)
  {
    id: 'fal-ai/flux-2-max',
    label: 'Flux 2 Max',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: '최고 품질 Flux',
    meta: { quality: 'high', speed: 'standard', cost: 'high', badge: '최고품질', priceNote: '$0.07/MP' },
  },
  {
    id: 'fal-ai/flux-2-max/edit',
    label: 'Flux 2 Max Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: '최고 품질 이미지 편집',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$0.07/MP' },
  },
  // Seedream 4.5 (ByteDance) — 최소 1920px/면 → 1K 불가
  {
    id: 'fal-ai/bytedance/seedream/v4.5/text-to-image',
    label: 'Seedream 4.5',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: 'ByteDance 최신 이미지 생성',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', badge: '최신', priceNote: '$0.04/img' },
    constraints: { resolutions: ['2K', '4K'] },
  },
  {
    id: 'fal-ai/bytedance/seedream/v4.5/edit',
    label: 'Seedream 4.5 Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: 'ByteDance 최신 이미지 편집',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.04/img' },
    constraints: { resolutions: ['2K', '4K'] },
  },
  // Seedream 4.0 (ByteDance)
  {
    id: 'fal-ai/bytedance/seedream/v4/text-to-image',
    label: 'Seedream 4.0',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: 'ByteDance 안정적 이미지 생성',
    meta: { quality: 'high', speed: 'standard', cost: 'low', priceNote: '$0.03/img' },
  },
  {
    id: 'fal-ai/bytedance/seedream/v4/edit',
    label: 'Seedream 4.0 Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: 'ByteDance 안정적 이미지 편집',
    meta: { quality: 'high', speed: 'standard', cost: 'low', priceNote: '$0.03/img' },
  },
  // GPT Image 1.5 (OpenAI via fal)
  {
    id: 'fal-ai/gpt-image-1.5',
    label: 'GPT Image 1.5',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: 'OpenAI 초저가 이미지 생성',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', badge: '최저가', priceNote: '$0.001' },
    constraints: { resolutions: ['1K'], aspectRatios: ['1:1', '16:9', '9:16'] },
  },
  {
    id: 'fal-ai/gpt-image-1.5/edit',
    label: 'GPT Image 1.5 Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: 'OpenAI 초저가 이미지 편집',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', priceNote: '$0.001' },
    constraints: { maxRefImages: 1, resolutions: ['1K'], aspectRatios: ['1:1', '16:9', '9:16'] },
  },
  // Reve (fal) — T2I: aspect_ratio enum만 지원, Edit: 단일 이미지 + 사이즈 파라미터 없음
  {
    id: 'fal-ai/reve/text-to-image',
    label: 'Reve',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: 'Reve 이미지 생성',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.04/img' },
    constraints: {
      aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3'],
      resolutions: ['1K'],
    },
  },
  {
    id: 'fal-ai/reve/edit',
    label: 'Reve Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: 'Reve 이미지 편집',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.04/img' },
    constraints: { maxRefImages: 1 },
  },
  // Wan 2.6 (Alibaba via fal) — 최대 ~1280px → 1K만
  {
    id: 'wan/v2.6/text-to-image',
    label: 'Wan 2.6',
    provider: 'fal',
    capabilities: ['text-to-image'],
    description: 'Alibaba Wan 이미지 생성',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', priceNote: '~$0.01/img' },
    constraints: { resolutions: ['1K'] },
  },
  {
    id: 'wan/v2.6/image-to-image',
    label: 'Wan 2.6 Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: 'Alibaba Wan 이미지 편집',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', priceNote: '~$0.01/img' },
    constraints: { maxRefImages: 1, resolutions: ['1K'] },
  },
  // Legacy: Gemini via kieai/fal
  {
    id: 'nano-banana-pro',
    label: 'Nano Banana Pro',
    provider: 'kieai',
    capabilities: ['text-to-image'],
    description: '고품질 이미지 생성',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$0.09/img' },
  },
  {
    id: 'fal-ai/nano-banana-pro/edit',
    label: 'Nano Banana Pro Edit',
    provider: 'fal',
    capabilities: ['image-to-image'],
    description: '고품질 이미지 편집 (14장 참조)',
    meta: { quality: 'high', speed: 'standard', cost: 'high', priceNote: '$0.15/img' },
    constraints: { maxRefImages: 14 },
  },
  // Gemini Direct API — fallback 전용 (enabled에서 비활성)
  {
    id: 'gemini-3-pro-image-preview',
    label: 'Gemini 3 Pro (Direct)',
    provider: 'gemini',
    capabilities: ['text-to-image', 'image-to-image'],
    description: 'Gemini 직접 API (fallback)',
    meta: { quality: 'high', speed: 'standard', cost: 'medium' },
    constraints: { maxRefImages: 10 },
  },
  {
    id: 'gemini-2.5-flash-image',
    label: 'Gemini 2.5 Flash (Direct)',
    provider: 'gemini',
    capabilities: ['text-to-image', 'image-to-image'],
    description: 'Gemini Flash 직접 API (fallback)',
    meta: { quality: 'standard', speed: 'fast', cost: 'low' },
    constraints: { maxRefImages: 8 },
  },

  // ─── TTS ───
  {
    id: 'fal-ai/elevenlabs/tts/multilingual-v2',
    label: 'ElevenLabs Multilingual v2',
    provider: 'fal',
    capabilities: ['tts'],
    description: '한국어 포함 다국어',
    meta: { quality: 'high', speed: 'standard', cost: 'medium', priceNote: '$0.10/1000자' },
    constraints: { languages: ['ko', 'en', 'ja', 'zh'] },
  },
  {
    id: 'fal-ai/elevenlabs/tts/turbo-v2.5',
    label: 'ElevenLabs Turbo 2.5',
    provider: 'fal',
    capabilities: ['tts'],
    description: '빠른 생성, 영어 최적화',
    meta: { quality: 'standard', speed: 'fast', cost: 'low', priceNote: '$0.05/1000자' },
    constraints: { languages: ['en'] },
  },
  {
    id: 'elevenlabs/text-to-speech-multilingual-v2',
    label: 'ElevenLabs Multilingual v2 (kieai)',
    provider: 'kieai',
    capabilities: ['tts'],
    description: '한국어 다국어 (kieai 경유)',
    meta: { quality: 'high', speed: 'standard', cost: 'medium' },
    constraints: { languages: ['ko', 'en', 'ja'] },
  },
  {
    id: 'elevenlabs/text-to-speech-turbo-2-5',
    label: 'ElevenLabs Turbo 2.5 (kieai)',
    provider: 'kieai',
    capabilities: ['tts'],
    description: '빠른 생성 (kieai 경유)',
    meta: { quality: 'standard', speed: 'fast', cost: 'low' },
    constraints: { languages: ['en'] },
  },

  // ─── BGM ───
  {
    id: 'V4_5',
    label: 'Suno V4.5',
    provider: 'kieai',
    capabilities: ['bgm'],
    description: '균형 잡힌 품질',
    meta: { quality: 'high', speed: 'standard', cost: 'medium' },
  },
  {
    id: 'V5',
    label: 'Suno V5',
    provider: 'kieai',
    capabilities: ['bgm'],
    description: '최신 모델',
    meta: { quality: 'high', speed: 'standard', cost: 'high', badge: '최신' },
  },
  {
    id: 'V4_5PLUS',
    label: 'Suno V4.5+',
    provider: 'kieai',
    capabilities: ['bgm'],
    description: '향상된 V4.5',
    meta: { quality: 'high', speed: 'standard', cost: 'medium' },
  },
  {
    id: 'V4',
    label: 'Suno V4',
    provider: 'kieai',
    capabilities: ['bgm'],
    description: '빠른 생성',
    meta: { quality: 'standard', speed: 'fast', cost: 'low' },
  },
  {
    id: 'V3_5',
    label: 'Suno V3.5',
    provider: 'kieai',
    capabilities: ['bgm'],
    description: '가장 빠름',
    meta: { quality: 'standard', speed: 'fast', cost: 'low' },
  },
]
